// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnbdxhsinqifhsdnybon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuYmR4aHNpbnFpZmhzZG55Ym9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0Mjg5NzUsImV4cCI6MjA3MTAwNDk3NX0.2Xo9z79IIl6eExsEa7RK53DrF4UIRo42cEREezswN4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});